# Generated by Django 4.1.7 on 2023-10-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(db_column='uid', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
